name: life_pilot
description: "Life Pilot - personal assistance recurring task manager & alarm clock"
publish_to: "none"
version: 1.0.0+1

environment: 
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_local_notifications: ^22.0.1
  timezone: ^0.11.0
  android_alarm_manager_plus: ^5.0.0
  fl_chart: ^1.2.0
  table_calendar: ^3.1.3
  google_fonts: ^8.1.0
  audioplayers: ^6.1.0
  file_selector: ^1.0.3
  path_provider: ^2.1.6
  uuid: ^4.5.1
  intl: ^0.20.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/logo/
    - assets/splash/


flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/image/orignal/logo/light.png"

  adaptive_icon_foreground: "assets/image/orignal/logo/light.png"
  adaptive_icon_background: "#FFF8E8"

flutter_native_splash:
  color: "#FFF8E8"
  image: assets/image/orignal/splash/light.png

  color_dark: "#0F3D2E"
  image_dark: assets/image/orignal/splash/dark.png

  android: true
  ios: true

  android_12:
    image: assets/image/orignal/splash/light.png
    image_dark: assets/image/orignal/splash/dark.png
    icon_background_color: "#FFF8E8"
    icon_background_color_dark: "#0F3D2E"